[
  {
    "numero": 1,
    "nombre": "Bulbasaur",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 2,
    "nombre": "Ivysaur",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Normal"
  },
  {
    "numero": 3,
    "nombre": "Venusaur",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 4,
    "nombre": "Charmander",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 5,
    "nombre": "Charmeleon",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Normal"
  },
  {
    "numero": 6,
    "nombre": "Charizard",
    "tipo1": "Fuego",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 7,
    "nombre": "Squirtle",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Dulce",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 8,
    "nombre": "Wartortle",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Normal"
  },
  {
    "numero": 9,
    "nombre": "Blastoise",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 10,
    "nombre": "Caterpie",
    "tipo1": "Bicho",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 11,
    "nombre": "Metapod",
    "tipo1": "Bicho",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Normal"
  },
  {
    "numero": 12,
    "nombre": "Butterfree",
    "tipo1": "Bicho",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 13,
    "nombre": "Weedle",
    "tipo1": "Bicho",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 14,
    "nombre": "Kakuna",
    "tipo1": "Bicho",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Normal"
  },
  {
    "numero": 15,
    "nombre": "Beedrill",
    "tipo1": "Bicho",
    "tipo2": "Veneno",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 16,
    "nombre": "Pidgey",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 17,
    "nombre": "Pidgeotto",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Normal"
  },
  {
    "numero": 18,
    "nombre": "Pidgeot",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 19,
    "nombre": "Rattata",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 20,
    "nombre": "Raticate",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 21,
    "nombre": "Spearow",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Campo",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 22,
    "nombre": "Fearow",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Campo",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 23,
    "nombre": "Ekans",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 24,
    "nombre": "Arbok",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 25,
    "nombre": "Pikachu",
    "tipo1": "Electrico",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 26,
    "nombre": "Raichu",
    "tipo1": "Electrico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 27,
    "nombre": "Sandshrew",
    "tipo1": "Tierra",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Campo",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 28,
    "nombre": "Sandslash",
    "tipo1": "Tierra",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Campo",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 29,
    "nombre": "Nidoranâ™€",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "hembra",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 30,
    "nombre": "Nidorina",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "hembra",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 31,
    "nombre": "Nidoqueen",
    "tipo1": "Veneno",
    "tipo2": "Tierra",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "hembra",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 32,
    "nombre": "Nidoranâ™‚",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "macho",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 33,
    "nombre": "Nidorino",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "macho",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 34,
    "nombre": "Nidoking",
    "tipo1": "Veneno",
    "tipo2": "Tierra",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "macho",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 35,
    "nombre": "Clefairy",
    "tipo1": "Hada",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 36,
    "nombre": "Clefable",
    "tipo1": "Hada",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 37,
    "nombre": "Vulpix",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 38,
    "nombre": "Ninetales",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 39,
    "nombre": "Jigglypuff",
    "tipo1": "Normal",
    "tipo2": "Hada",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 40,
    "nombre": "Wigglytuff",
    "tipo1": "Normal",
    "tipo2": "Hada",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 41,
    "nombre": "Zubat",
    "tipo1": "Veneno",
    "tipo2": "Volador",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Caverna",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 42,
    "nombre": "Golbat",
    "tipo1": "Veneno",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Caverna",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 43,
    "nombre": "Oddish",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 44,
    "nombre": "Gloom",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 45,
    "nombre": "Vileplume",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 46,
    "nombre": "Paras",
    "tipo1": "Bicho",
    "tipo2": "Planta",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 47,
    "nombre": "Parasect",
    "tipo1": "Bicho",
    "tipo2": "Planta",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 48,
    "nombre": "Venonat",
    "tipo1": "Bicho",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 49,
    "nombre": "Venomoth",
    "tipo1": "Bicho",
    "tipo2": "Veneno",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 50,
    "nombre": "Diglett",
    "tipo1": "Tierra",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Caverna",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 51,
    "nombre": "Dugtrio",
    "tipo1": "Tierra",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Caverna",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 52,
    "nombre": "Meowth",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 53,
    "nombre": "Persian",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 54,
    "nombre": "Psyduck",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 55,
    "nombre": "Golduck",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 56,
    "nombre": "Mankey",
    "tipo1": "Lucha",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 57,
    "nombre": "Primeape",
    "tipo1": "Lucha",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 58,
    "nombre": "Growlithe",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 59,
    "nombre": "Arcanine",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 60,
    "nombre": "Poliwag",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 61,
    "nombre": "Poliwhirl",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 62,
    "nombre": "Poliwrath",
    "tipo1": "Agua",
    "tipo2": "Lucha",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 63,
    "nombre": "Abra",
    "tipo1": "Psiquico",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 64,
    "nombre": "Kadabra",
    "tipo1": "Psiquico",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Intercambio"
  },
  {
    "numero": 65,
    "nombre": "Alakazam",
    "tipo1": "Psiquico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 66,
    "nombre": "Machop",
    "tipo1": "Lucha",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 67,
    "nombre": "Machoke",
    "tipo1": "Lucha",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Intercambio"
  },
  {
    "numero": 68,
    "nombre": "Machamp",
    "tipo1": "Lucha",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 69,
    "nombre": "Bellsprout",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 70,
    "nombre": "Weepinbell",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 71,
    "nombre": "Victreebel",
    "tipo1": "Planta",
    "tipo2": "Veneno",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 72,
    "nombre": "Tentacool",
    "tipo1": "Agua",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Salada",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 73,
    "nombre": "Tentacruel",
    "tipo1": "Agua",
    "tipo2": "Veneno",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 74,
    "nombre": "Geodude",
    "tipo1": "Roca",
    "tipo2": "Tierra",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 75,
    "nombre": "Graveler",
    "tipo1": "Roca",
    "tipo2": "Tierra",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Intercambio"
  },
  {
    "numero": 76,
    "nombre": "Golem",
    "tipo1": "Roca",
    "tipo2": "Tierra",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 77,
    "nombre": "Ponyta",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 78,
    "nombre": "Rapidash",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 79,
    "nombre": "Slowpoke",
    "tipo1": "Agua",
    "tipo2": "Psiquico",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 80,
    "nombre": "Slowbro",
    "tipo1": "Agua",
    "tipo2": "Psiquico",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 81,
    "nombre": "Magnemite",
    "tipo1": "Electrico",
    "tipo2": "Acero",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Campo",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 82,
    "nombre": "Magneton",
    "tipo1": "Electrico",
    "tipo2": "Acero",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Campo",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 83,
    "nombre": "Farfetch'd",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 84,
    "nombre": "Doduo",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 85,
    "nombre": "Dodrio",
    "tipo1": "Normal",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 86,
    "nombre": "Seel",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Salada",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 87,
    "nombre": "Dewgong",
    "tipo1": "Agua",
    "tipo2": "Hielo",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 88,
    "nombre": "Grimer",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 89,
    "nombre": "Muk",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 90,
    "nombre": "Shellder",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Salada",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 91,
    "nombre": "Cloyster",
    "tipo1": "Agua",
    "tipo2": "Hielo",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 92,
    "nombre": "Gastly",
    "tipo1": "Fantasma",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Caverna",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 93,
    "nombre": "Haunter",
    "tipo1": "Fantasma",
    "tipo2": "Veneno",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Caverna",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Intercambio"
  },
  {
    "numero": 94,
    "nombre": "Gengar",
    "tipo1": "Fantasma",
    "tipo2": "Veneno",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Caverna",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 95,
    "nombre": "Onix",
    "tipo1": "Roca",
    "tipo2": "Tierra",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Caverna",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 96,
    "nombre": "Drowzee",
    "tipo1": "Psiquico",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 97,
    "nombre": "Hypno",
    "tipo1": "Psiquico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 98,
    "nombre": "Krabby",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 99,
    "nombre": "Kingler",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 100,
    "nombre": "Voltorb",
    "tipo1": "Electrico",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 101,
    "nombre": "Electrode",
    "tipo1": "Electrico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 102,
    "nombre": "Exeggcute",
    "tipo1": "Planta",
    "tipo2": "Psiquico",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 103,
    "nombre": "Exeggutor",
    "tipo1": "Planta",
    "tipo2": "Psiquico",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 104,
    "nombre": "Cubone",
    "tipo1": "Tierra",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 105,
    "nombre": "Marowak",
    "tipo1": "Tierra",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 106,
    "nombre": "Hitmonlee",
    "tipo1": "Lucha",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"

  },
  {
    "numero": 107,
    "nombre": "Hitmonchan",
    "tipo1": "Lucha",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 108,
    "nombre": "Lickitung",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 109,
    "nombre": "Koffing",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 110,
    "nombre": "Weezing",
    "tipo1": "Veneno",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Levita",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 111,
    "nombre": "Rhyhorn",
    "tipo1": "Tierra",
    "tipo2": "Roca",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Campo",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 112,
    "nombre": "Rhydon",
    "tipo1": "Tierra",
    "tipo2": "Roca",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Campo",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 113,
    "nombre": "Chansey",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Hembra",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 114,
    "nombre": "Tangela",
    "tipo1": "Planta",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 115,
    "nombre": "Kangaskhan",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Zona Safari",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 116,
    "nombre": "Horsea",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Salada",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 117,
    "nombre": "Seadra",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 118,
    "nombre": "Goldeen",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 119,
    "nombre": "Seaking",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 120,
    "nombre": "Staryu",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Salada",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 121,
    "nombre": "Starmie",
    "tipo1": "Agua",
    "tipo2": "Psiquico",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 122,
    "nombre": "Mr-Mime",
    "tipo1": "Psiquico",
    "tipo2": "Hada",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 123,
    "nombre": "Scyther",
    "tipo1": "Bicho",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 124,
    "nombre": "Jynx",
    "tipo1": "Hielo",
    "tipo2": "Psiquico",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 125,
    "nombre": "Electabuzz",
    "tipo1": "Electrico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Pradera",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 126,
    "nombre": "Magmar",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 127,
    "nombre": "Pinsir",
    "tipo1": "Bicho",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Bosque",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 128,
    "nombre": "Tauros",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Zona Safari",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 129,
    "nombre": "Magikarp",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "comun",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 130,
    "nombre": "Gyarados",
    "tipo1": "Agua",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 131,
    "nombre": "Lapras",
    "tipo1": "Agua",
    "tipo2": "Hielo",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Nada",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 132,
    "nombre": "Ditto",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 133,
    "nombre": "Eevee",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Piedra"
  },
  {
    "numero": 134,
    "nombre": "Vaporeon",
    "tipo1": "Agua",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 135,
    "nombre": "Jolteon",
    "tipo1": "Electrico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 136,
    "nombre": "Flareon",
    "tipo1": "Fuego",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "poco comun",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 137,
    "nombre": "Porygon",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Ciudad",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 138,
    "nombre": "Omanyte",
    "tipo1": "Roca",
    "tipo2": "Agua",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Salada",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 139,
    "nombre": "Omastar",
    "tipo1": "Roca",
    "tipo2": "Agua",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 140,
    "nombre": "Kabuto",
    "tipo1": "Roca",
    "tipo2": "Agua",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Salada",
    "cant_evo": 1,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 141,
    "nombre": "Kabutops",
    "tipo1": "Roca",
    "tipo2": "Agua",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Salada",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 142,
    "nombre": "Aerodactyl",
    "tipo1": "Roca",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 143,
    "nombre": "Snorlax",
    "tipo1": "Normal",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Montaña",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 144,
    "nombre": "Articuno",
    "tipo1": "Hielo",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Raro",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 145,
    "nombre": "Zapdos",
    "tipo1": "Electrico",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Raro",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 146,
    "nombre": "Moltres",
    "tipo1": "Fuego",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Vuela",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Raro",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 147,
    "nombre": "Dratini",
    "tipo1": "Dragon",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Dulce",
    "cant_evo": 2,
    "evolucionado": "NO",
    "tipo_evo": "Normal"
  },
  {
    "numero": 148,
    "nombre": "Dragonair",
    "tipo1": "Dragon",
    "tipo2": "No Tiene",
    "evoluciona": "SI",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Dulce",
    "cant_evo": 1,
    "evolucionado": "SI",
    "tipo_evo": "Normal"
  },
  {
    "numero": 149,
    "nombre": "Dragonite",
    "tipo1": "Dragon",
    "tipo2": "Volador",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Agua Dulce",
    "cant_evo": 0,
    "evolucionado": "SI",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 150,
    "nombre": "Mewtwo",
    "tipo1": "Psiquico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "NO",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Raro",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  },
  {
    "numero": 151,
    "nombre": "Mew",
    "tipo1": "Psiquico",
    "tipo2": "No Tiene",
    "evoluciona": "NO",
    "animal": "SI",
    "accion": "Camina",
    "sexo": "Ambos",
    "raro": "raro",
    "habitat": "Raro",
    "cant_evo": 0,
    "evolucionado": "NO",
    "tipo_evo": "No tiene"
  }
]